FROM python:3.9
WORKDIR /app
COPY . /app
RUN | \
    python -m venv venv \
    source venv/bin/activate \
    pip install  -r requirements.txt
EXPOSE 80
ARG SECRET_API_KEY
ARG DATABASE_URL
ARG SECRET_PASSWORD_KEY
ARG ALGORITHM

ENV API_KEY=$SECRET_API_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV SECRET_PASSWORD_KEY=$SECRET_PASSWORD_KEY
ENV ALGORITHM=$ALGORITHM

CMD ["python", "app.py"]