FROM python:3.10-slim
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
EXPOSE 80
ARG SECRET_EN_KEY
ARG DATABASE_URL
ARG SECRET_PASSWORD_KEY
ARG ALGORITHM

ENV EN_KEY=$SECRET_EN_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV SECRET_PASSWORD_KEY=$SECRET_PASSWORD_KEY
ENV ALGORITHM=$ALGORITHM

CMD ["python", "main.py"]